language: java

before_script:
  - java -jar src/test/resources/wiremock-standalone-2.17.0.jar --port 9876 & pid=$!
  - echo $pid

tests:
  provider: script
  script:
  - mvn -X test

after_script:
  - echo $pid
  - kill -KILL $pid